name: Deploy images

on:
  workflow_dispatch:
    inputs:
      build_only:
        description: Build only? (true|false)
        required: false
        default: 'false'

jobs:
  py27:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build and deploy image 🐳
        uses: docker/build-push-action@v1
        with:
          path: docker
          dockerfile: docker/Dockerfile_27
          repository: cmsml/cmsml
          tags: 2.7,2
          push: ${{ github.event.inputs.build_only != 'true' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  py37:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build and deploy image 🐳
        uses: docker/build-push-action@v1
        with:
          path: docker
          dockerfile: docker/Dockerfile_37
          repository: cmsml/cmsml
          tags: 3.7
          push: ${{ github.event.inputs.build_only != 'true' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  py38:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build and deploy image 🐳
        uses: docker/build-push-action@v1
        with:
          path: docker
          dockerfile: docker/Dockerfile_38
          repository: cmsml/cmsml
          tags: 3.8
          push: ${{ github.event.inputs.build_only != 'true' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  py39:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build and deploy image 🐳
        uses: docker/build-push-action@v1
        with:
          path: docker
          dockerfile: docker/Dockerfile_39
          repository: cmsml/cmsml
          tags: 3.9,3,latest
          push: ${{ github.event.inputs.build_only != 'true' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  docs:
    needs: py39
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_only != 'true' }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build and deploy image 🐳
        uses: docker/build-push-action@v1
        with:
          path: docker
          dockerfile: docker/Dockerfile_docs
          repository: cmsml/cmsml
          tags: docs
          push: ${{ github.event.inputs.build_only != 'true' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
